define encyclopaedia.sort_by_number = _("Number")
define encyclopaedia.sort_by_alphabetical = _("A to Z")
define encyclopaedia.sort_by_reverse_alphabetical = _("Z to A")
define encyclopaedia.sort_by_subject = _("Subject")
define encyclopaedia.sort_by_unread = _("Unread")
