exclude = ["docs"]
line-length = 99

[lint.mccabe]
max-complexity = 8

[lint.per-file-ignores]
"**/tests/*" = ["D","S101","B018"]
"**/encyclopaedia/encyclopaedia_ren.py" = ["N802"]

[lint.pydocstyle]
convention = "google"

[lint]
select = [
"A",
"B",
"BLE",
"C4",
"COM",
"C90",
"D",
"E",
"F",
"N",
"PTH",
"RUF",
"S",
"SLOT",
"T20",
"TRY",
"W",
]

ignore = [
"B026",
"D100",
"D107",
"D204",
"D413",
"D415",
"F405",
"F821",
"RUF010",
"TRY003",
]
